### Feature extractions

This script extracted features from two sentimental corpora, kt4.0 (ours) and wisesight. By training from kt4.0 corpus, we expect to see an improvement in the wisesight corpus' classification performance.

Several feature extraction methods were applied on text feature to both corpuses as follows:  

* Bag of words for unigram and bigrams
* TF-IDF for unigram and bigrams
* Word2Vec with TF-IDF vector (300 dimension)
* POS_tagging with flatten dataframe for unigram and bigrams
* Dictionary-based with list of Thai positive and negative words for unigram and bigrams

Output:  
for all the feature extraction methods above, Joblib objects as numpy array and sparse matrix on text feature were dumped.     
pree.t@cmu.ac.th  

Todo:   
* add thaitale corpus  

In [1]:
import pandas as pd
import numpy as np
import pythainlp
import re
import emoji
import emot
from pythainlp import word_tokenize

# for visualize
from matplotlib import pyplot as plt
plt.rcParams['font.family'] = 'tahoma'

## Load original datasets

In [2]:
import os
from emot.emo_unicode import UNICODE_EMOJI
    
os.path.dirname(os.getcwd())

data_path_kt = os.path.dirname(os.getcwd()) + '\\data\kt4.0\\'
data_path_ws = os.path.dirname(os.getcwd()) + '\\data\wisesight\\'
model_path = os.path.dirname(os.getcwd()) + '\\model\\'
lexicon_path = os.path.dirname(os.getcwd()) + '\\lexicon\\'

df_kt = pd.read_csv(data_path_kt + 'pantip_cleaned_1.csv')

# we use the original wisesight corpus and reconstruct a new dataframe
texts = []
targets = []

with open(str(data_path_ws) + '\\' + 'neg.txt', encoding='utf-8') as f:
    for line in f:
        texts.append(line.strip())
        targets.append('neg')

with open(str(data_path_ws) + '\\' + 'neu.txt', encoding='utf-8') as f:
    for line in f:
        texts.append(line.strip())
        targets.append('neu')

with open(str(data_path_ws) + '\\' + 'pos.txt', encoding='utf-8') as f:
    for line in f:
        texts.append(line.strip())
        targets.append('pos')

with open(str(data_path_ws) + '\\' + 'q.txt', encoding='utf-8') as f:
    for line in f:
        texts.append(line.strip())
        targets.append('q')
        
df_ws = pd.DataFrame({'texts': texts, 'targets': targets})
df_ws.to_csv(os.path.dirname(os.getcwd()) + '\\' + 'wisesight.csv', index=False)
df_kt.shape, df_ws.shape

((60081, 14), (26737, 2))

In [3]:
y_kt = df_kt['vote'].astype('category').cat.codes
y_ws = df_ws['targets'].astype('category').cat.codes
y_kt.unique(), y_ws.unique()

(array([2, 0, 1], dtype=int8), array([0, 1, 2, 3], dtype=int8))

In [4]:
def replace_url(text):
    URL_PATTERN = r"""(?i)\b((?:https?:(?:/{1,3}|[a-z0-9%])|[a-z0-9.\-]+[.](?:com|net|org|edu|gov|mil|aero|asia|biz|cat|coop|info|int|jobs|mobi|museum|name|post|pro|tel|travel|xxx|ac|ad|ae|af|ag|ai|al|am|an|ao|aq|ar|as|at|au|aw|ax|az|ba|bb|bd|be|bf|bg|bh|bi|bj|bm|bn|bo|br|bs|bt|bv|bw|by|bz|ca|cc|cd|cf|cg|ch|ci|ck|cl|cm|cn|co|cr|cs|cu|cv|cx|cy|cz|dd|de|dj|dk|dm|do|dz|ec|ee|eg|eh|er|es|et|eu|fi|fj|fk|fm|fo|fr|ga|gb|gd|ge|gf|gg|gh|gi|gl|gm|gn|gp|gq|gr|gs|gt|gu|gw|gy|hk|hm|hn|hr|ht|hu|id|ie|il|im|in|io|iq|ir|is|it|je|jm|jo|jp|ke|kg|kh|ki|km|kn|kp|kr|kw|ky|kz|la|lb|lc|li|lk|lr|ls|lt|lu|lv|ly|ma|mc|md|me|mg|mh|mk|ml|mm|mn|mo|mp|mq|mr|ms|mt|mu|mv|mw|mx|my|mz|na|nc|ne|nf|ng|ni|nl|no|np|nr|nu|nz|om|pa|pe|pf|pg|ph|pk|pl|pm|pn|pr|ps|pt|pw|py|qa|re|ro|rs|ru|rw|sa|sb|sc|sd|se|sg|sh|si|sj|Ja|sk|sl|sm|sn|so|sr|ss|st|su|sv|sx|sy|sz|tc|td|tf|tg|th|tj|tk|tl|tm|tn|to|tp|tr|tt|tv|tw|tz|ua|ug|uk|us|uy|uz|va|vc|ve|vg|vi|vn|vu|wf|ws|ye|yt|yu|za|zm|zw)/)(?:[^\s()<>{}\[\]]+|\([^\s()]*?\([^\s()]+\)[^\s()]*?\)|\([^\s]+?\))+(?:\([^\s()]*?\([^\s()]+\)[^\s()]*?\)|\([^\s]+?\)|[^\s`!()\[\]{};:'".,<>?«»“”‘’])|(?:(?<!@)[a-z0-9]+(?:[.\-][a-z0-9]+)*[.](?:com|net|org|edu|gov|mil|aero|asia|biz|cat|coop|info|int|jobs|mobi|museum|name|post|pro|tel|travel|xxx|ac|ad|ae|af|ag|ai|al|am|an|ao|aq|ar|as|at|au|aw|ax|az|ba|bb|bd|be|bf|bg|bh|bi|bj|bm|bn|bo|br|bs|bt|bv|bw|by|bz|ca|cc|cd|cf|cg|ch|ci|ck|cl|cm|cn|co|cr|cs|cu|cv|cx|cy|cz|dd|de|dj|dk|dm|do|dz|ec|ee|eg|eh|er|es|et|eu|fi|fj|fk|fm|fo|fr|ga|gb|gd|ge|gf|gg|gh|gi|gl|gm|gn|gp|gq|gr|gs|gt|gu|gw|gy|hk|hm|hn|hr|ht|hu|id|ie|il|im|in|io|iq|ir|is|it|je|jm|jo|jp|ke|kg|kh|ki|km|kn|kp|kr|kw|ky|kz|la|lb|lc|li|lk|lr|ls|lt|lu|lv|ly|ma|mc|md|me|mg|mh|mk|ml|mm|mn|mo|mp|mq|mr|ms|mt|mu|mv|mw|mx|my|mz|na|nc|ne|nf|ng|ni|nl|no|np|nr|nu|nz|om|pa|pe|pf|pg|ph|pk|pl|pm|pn|pr|ps|pt|pw|py|qa|re|ro|rs|ru|rw|sa|sb|sc|sd|se|sg|sh|si|sj|Ja|sk|sl|sm|sn|so|sr|ss|st|su|sv|sx|sy|sz|tc|td|tf|tg|th|tj|tk|tl|tm|tn|to|tp|tr|tt|tv|tw|tz|ua|ug|uk|us|uy|uz|va|vc|ve|vg|vi|vn|vu|wf|ws|ye|yt|yu|za|zm|zw)\b/?(?!@)))"""
    return re.sub(URL_PATTERN, 'xxurl', text)

def replace_rep(text):
    def _replace_rep(m):
        c,cc = m.groups()
        return f'{c}xxrep'
    re_rep = re.compile(r'(\S)(\1{2,})')
    return re_rep.sub(_replace_rep, text)
    

def convert_emojis(text):
    for emot in UNICODE_EMOJI:
        text = text.replace(emot, "_".join(UNICODE_EMOJI[emot].replace("_", "-").replace(",","").replace(":","EMJ").split()))
    return text  

def ungroup_emoji(toks):
    res = []
    for tok in toks:
        if emoji.emoji_count(tok) == len(tok):
            for char in tok:
                res.append(char)
        else:
            res.append(tok)
    return res

def remove_all_extra_spaces(text):
    return " ".join(text.split())

def remove_word_len(text):
    new_list = [ word for word in text if len(word) >= 2 ]
    return new_list

def process_text(text):
    #pre rules
    res = text.lower().strip()
    res = replace_url(res)
    res = convert_emojis(res)
    res = replace_rep(res)
    
    #tokenize with the newmm algo.
    res = [word for word in word_tokenize(res, engine='newmm', keep_whitespace=False)if word and not re.search(pattern=r"\s+", string=word)]
    
    #post rules
    res = ungroup_emoji(res)
    res = remove_word_len(res)
    return res

In [5]:
df_kt['processed'] = df_kt['text'].apply(str).apply(process_text)
df_ws['processed'] = df_ws['texts'].apply(str).apply(process_text)

In [6]:
df_ws[0:10]

texts targets                      processed
0    ☹️     neg          [EMJfrowning-faceEMJ]
1     😔     neg           [EMJpensive-faceEMJ]
2     😞     neg      [EMJdisappointed-faceEMJ]
3     😥     neg  [EMJsad-but-relieved-faceEMJ]
4    รำ     neg                           [รำ]
5   Noๆ     neg                           [no]
6   Rip     neg                          [rip]
7   T_T     neg                             []
8   กาก     neg                          [กาก]
9   โกง     neg                          [โกง]

In [7]:
df_kt.head(10)

post_id            post_date                             user_id  \
0  39839097  2020-04-25 13:24:00  https://pantip.com/profile/5798163   
1  39839097  2020-04-25 13:24:00  https://pantip.com/profile/5798163   
2  39839097  2020-04-25 13:24:00  https://pantip.com/profile/5798163   
3  39838736  2020-04-25 10:52:00  https://pantip.com/profile/5730006   
4  39837384  2020-04-24 20:39:00  https://pantip.com/profile/4975838   
5  39838990  2020-04-25 12:36:00  https://pantip.com/profile/5655853   
6  39838619  2020-04-25 10:01:00  https://pantip.com/profile/5656639   
7  39837266  2020-04-24 19:58:00   https://pantip.com/profile/632132   
8  39837266  2020-04-24 19:58:00   https://pantip.com/profile/632132   
9  39835926  2020-04-24 12:03:00  https://pantip.com/profile/3826851   

               user_name                                               text  \
0  สมาชิกหมายเลข 5798163              [CR] แปังพัฟคุมมัน จัดเต็มเนื้อบางเบา   
1  สมาชิกหมายเลข 5798163                          ไม่อุดตัน แต่ปกปิดแน่นมาก   
2  สมาชิกหมายเลข 5798163            รีวิวแป้ง Lady Audrey Ready All Day จ้า   
3  สมาชิกหมายเลข 5730006            ขอบตาดำมากค่ะ คอร์เล็คเตอร์ก็เอาไม่อยู่   
4  สมาชิกหมายเลข 4975838          เอาaloe Vera แช่ตู้เย็น จนกลายเป็นน้ำแข็ง   
5                chdewxx  [SR] ไอเทม #เซรั่มสิว ลดสิว สิวอุดตัน สิวผด บำ...   
6       คูจองยอนและวีรยา  รบกวนสาวๆช่วยแนะนำสกินแคร์ ที่ช่วยให้ผิวหน้าขา...   
7         หมูกลมอารมณ์ดี                          ทดลองใช้ แครอทวิตซีหน้าใส   
8         หมูกลมอารมณ์ดี                                       ใน 1 สัปดาห์   
9  สมาชิกหมายเลข 3826851              วิธีเลือก "รองพื้น" และ "คอนซีลเลอร์"   

            tag                                          emotion  length  \
0  เครื่องสำอาง  ถูกใจ 0 ขำกลิ้ง 0 หลงรัก 0 ซึ้ง 0 สยอง 0 ทึ่ง 0      36   
1  เครื่องสำอาง  ถูกใจ 0 ขำกลิ้ง 0 หลงรัก 0 ซึ้ง 0 สยอง 0 ทึ่ง 0      36   
2  เครื่องสำอาง  ถูกใจ 0 ขำกลิ้ง 0 หลงรัก 0 ซึ้ง 0 สยอง 0 ทึ่ง 0      36   
3  เครื่องสำอาง  ถูกใจ 0 ขำกลิ้ง 0 หลงรัก 0 ซึ้ง 0 สยอง 0 ทึ่ง 0      15   
4  เครื่องสำอาง  ถูกใจ 0 ขำกลิ้ง 0 หลงรัก 0 ซึ้ง 0 สยอง 0 ทึ่ง 0      11   
5  เครื่องสำอาง  ถูกใจ 0 ขำกลิ้ง 0 หลงรัก 0 ซึ้ง 0 สยอง 0 ทึ่ง 0      29   
6  เครื่องสำอาง  ถูกใจ 0 ขำกลิ้ง 0 หลงรัก 0 ซึ้ง 0 สยอง 0 ทึ่ง 0      23   
7  เครื่องสำอาง  ถูกใจ 0 ขำกลิ้ง 0 หลงรัก 0 ซึ้ง 0 สยอง 0 ทึ่ง 0      14   
8  เครื่องสำอาง  ถูกใจ 0 ขำกลิ้ง 0 หลงรัก 0 ซึ้ง 0 สยอง 0 ทึ่ง 0      14   
9  เครื่องสำอาง  ถูกใจ 0 ขำกลิ้ง 0 หลงรัก 0 ซึ้ง 0 สยอง 0 ทึ่ง 0      14   

   num_sent  sent_length  label  label_1  label_2 vote  \
0         3           14      2        2        2  pos   
1         3            8      2        2        2  pos   
2         3           14      2        2        1  pos   
3         2           13      1        3        3  neg   
4         1           11      1        1        3  neu   
5         1           29      2        2        2  pos   
6         1           23      2        2        1  pos   
7         2            9      1        2        2  pos   
8         2            5      1        1        1  neu   
9         1           14      2        2        2  pos   

                                           processed  
0  [cr, แป, ังพัฟ, คุม, มัน, จัด, เต็ม, เนื้อ, บา...  
1               [ไม่, อุดตัน, แต่, ปกปิด, แน่น, มาก]  
2  [รีวิว, แป้ง, lady, audrey, ready, all, day, จ้า]  
3  [ขอบ, ตาดำ, มาก, ค่ะ, คอร์, เล็ค, เต, อร, ก็, ...  
4  [เอา, aloe, vera, แช่, ตู้เย็น, จน, กลายเป็น, ...  
5  [sr, ไอเทม, เซ, รั่ม, สิว, ลด, สิว, สิว, อุดตั...  
6  [รบกวน, สาว, ช่วย, แนะนำ, กิน, แคร์, ที่, ช่วย...  
7                [ทดลองใช้, แครอท, วิ, ซี, หน้า, ใส]  
8                                      [ใน, สัปดาห์]  
9    [วิธี, เลือก, รองพื้น, และ, คอน, ซีล, เลอ, ร์"]

In [8]:
df_kt.describe()

post_id        length      num_sent   sent_length         label  \
count  6.008100e+04  60081.000000  60081.000000  60081.000000  60081.000000   
mean   3.964936e+07    116.994574      8.502172     13.978329      1.577304   
std    1.559919e+05    118.647716      7.575442     12.083572      0.777527   
min    3.917283e+07      3.000000      1.000000      3.000000      1.000000   
25%    3.958755e+07     31.000000      3.000000      6.000000      1.000000   
50%    3.968929e+07     72.000000      6.000000     10.000000      1.000000   
75%    3.976947e+07    159.000000     11.000000     17.000000      2.000000   
max    3.983970e+07    499.000000     44.000000    301.000000      3.000000   

            label_1       label_2  
count  60081.000000  60081.000000  
mean       1.362644      1.662156  
std        0.639271      0.800034  
min        1.000000      1.000000  
25%        1.000000      1.000000  
50%        1.000000      1.000000  
75%        2.000000      2.000000  
max        3.000000      3.000000

In [9]:
df_ws.tail(10)

texts targets  \
26727  พี่ขวัญคะ ถ้าเรามี ซุลวาซุลเฟิร์สแคร์ กับ vich...       q   
26728  มีสาวผิวเหลืองคนไหนลองใช้รองพื้นรุ่นใหม่ล่าสุด...       q   
26729  แอดมินคะ ทำไม True Money Wallet หักเงินคงเหลือ...       q   
26730  แนะนำลิปของ cute press สีส้มอิฐหน่อยครับ อันไห...       q   
26731  เวลาวิ่งที่ความเร็ว 80 ขึ้นไปพวงมาลัยจะสั่นครั...       q   
26732  วิธีซื้อรถมือสองต้องดูยังไงดีครับตอนนั้นพีจิมแ...       q   
26733  - น้ำมันเครื่อง ทั้ง Fully / Semi เบนซิน - น้ำ...       q   
26734  Honda Civic Hatchback ที่มากับสีแดง ราคาเท่าเด...       q   
26735  กำลังจะเริ่ม skincare 2 ตัวคือ stemfactor กับ ...       q   
26736  พี่คะ หนูอยากสอบถามเรื่องนึงค่ะ อาจะไม่เกี่ยวก...       q   

                                               processed  
26727  [พี่, ขวัญ, คะ, ถ้า, เรา, มี, ซุล, วา, ซุลเฟิร...  
26728  [มี, สาว, ผิวเหลือง, คน, ไหน, ลอง, ใช้, รองพื้...  
26729  [แอดมิน, คะ, ทำไม, true, money, wallet, หัก, เ...  
26730  [แนะนำ, ลิป, ของ, cute, press, สีส้ม, อิฐ, หน่...  
26731  [เวลา, วิ่ง, ที่, ความเร็ว, 80, ขึ้นไป, พวงมาล...  
26732  [วิธี, ซื้อ, รถ, มือสอง, ต้อง, ดู, ยังไง, ดี, ...  
26733  [น้ำมันเครื่อง, ทั้ง, fully, semi, เบนซิน, น้ำ...  
26734  [honda, civic, hatchback, ที่มา, กับ, สีแดง, ร...  
26735  [กำลังจะ, เริ่ม, skincare, ตัว, คือ, stemfacto...  
26736  [พี่, คะ, หนู, อยาก, สอบถาม, เรื่อง, นึง, ค่ะ,...

In [10]:
df_ws.describe()

texts targets processed
count          26737   26737     26737
unique         26713       4     26383
top     อุดรมีไหมค่ะ     neu   [xxrep]
freq               2   14561        16

In [11]:
# class distribution
df_kt.vote.value_counts() / df_kt.shape[0]

neu    0.633378
pos    0.205822
neg    0.160800
Name: vote, dtype: float64

In [12]:
# class distribution
df_ws.targets.value_counts() / df_ws.shape[0]

neu    0.544601
neg    0.255189
pos    0.178704
q      0.021506
Name: targets, dtype: float64

## Bag of words 

In [25]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

# BOW with unigram and bigrams
bow1 = CountVectorizer(max_features =1394)
#bow2 = CountVectorizer(tokenizer=process_text, ngram_range=(2, 2), min_df=5)

# fit kt and transform to both datasets
bow1_fit_kt = bow1.fit(df_kt['text'].apply(str))
text_bow1_kt = bow1_fit_kt.transform(df_kt['text'].apply(str))
# lex_bow1_kt = bow1_fit_kt.get_feature_names()
# text_bow1_ws = bow1_fit_kt.transform(df_ws['texts'].apply(str))
# lex_bow1_ws = bow1_fit_kt.get_feature_names()

# bow2_fit_kt = bow2.fit(df_kt['text'].apply(str))
# text_bow2_kt = bow2_fit_kt.transform(df_kt['text'].apply(str))
# lex_bow2_kt = bow2_fit_kt.get_feature_names()
# text_bow2_ws = bow2_fit_kt.transform(df_ws['texts'].apply(str))
# lex_bow2_ws = bow2_fit_kt.get_feature_names()

# print(text_bow1_kt.toarray().shape,  text_bow1_kt.toarray().shape)
# print(text_bow2_kt.toarray().shape,  text_bow2_kt.toarray().shape)
# print("\n")
# print(text_bow1_ws.toarray().shape,  text_bow1_ws.toarray().shape)
# print(text_bow2_ws.toarray().shape,  text_bow2_ws.toarray().shape)
# print("\n")
# print(len(lex_bow1_kt), len(lex_bow1_ws))
# print(len(lex_bow2_kt), len(lex_bow2_ws))

In [ ]:
#visualize texts
from visualize import top_feats_all, plot_top_feats
features = bow1_fit_kt.get_feature_names()
%time ts = top_feats_all(text_bow1_kt.toarray(), y_kt, features)
print(ts[0].shape)
ts[0].head()

In [ ]:
%time plot_top_feats(ts)

## TF-IDF

In [ ]:
# TF-IDF with unigram and bigrams
tfidf1 = TfidfVectorizer(tokenizer=process_text, ngram_range=(1, 1), min_df=5)
tfidf2 = TfidfVectorizer(tokenizer=process_text, ngram_range=(2, 2), min_df=5)

# fit kt and transform to both datasets
tfidf1_fit_kt = tfidf1.fit(df_kt['text'].apply(str))
text_tfidf1_kt = tfidf1_fit_kt.transform(df_kt['text'].apply(str))
lex_tfidf1_kt = tfidf1_fit_kt.get_feature_names()
text_tfidf1_ws = tfidf1_fit_kt.transform(df_ws['texts'].apply(str))
lex_tfidf1_ws = tfidf1_fit_kt.get_feature_names()

tfidf2_fit_kt = tfidf2.fit(df_kt['text'].apply(str))
text_tfidf2_kt = tfidf2_fit_kt.transform(df_kt['text'].apply(str))
lex_tfidf2_kt = tfidf2_fit_kt.get_feature_names()
text_tfidf2_ws = tfidf2_fit_kt.transform(df_ws['texts'].apply(str))
lex_tfidf2_ws = tfidf2_fit_kt.get_feature_names()

print(text_tfidf1_kt.toarray().shape,  text_tfidf1_kt.toarray().shape)
print(text_tfidf2_kt.toarray().shape,  text_tfidf2_kt.toarray().shape)
print("\n")
print(text_tfidf1_ws.toarray().shape,  text_tfidf1_ws.toarray().shape)
print(text_tfidf2_ws.toarray().shape,  text_tfidf2_ws.toarray().shape)

print("\n")
print(len(lex_tfidf1_kt), len(lex_tfidf1_ws))
print(len(lex_tfidf2_kt), len(lex_tfidf2_ws))

## Word2vec

In [ ]:
from collections import Counter, defaultdict

class TfidfEmbeddingVectorizer(object):
    def __init__(self, model):
        w2v = {w: vec for w, vec in zip(model.wv.index_to_key, model.wv.vectors)}
        self.word2vec = w2v
        self.word2weight = None
        self.dim = model.vector_size
    
    def fit(self, X):
        tfidf = TfidfVectorizer(analyzer=lambda x: x)
        tfidf.fit(X)
        max_idf = max(tfidf.idf_)
        self.word2weight = defaultdict(
            lambda: max_idf,
            [(w, tfidf.idf_[i]) for w, i in tfidf.vocabulary_.items()])

        return self

    def transform(self, X):
        return np.array([
                np.mean([self.word2vec[w] * self.word2weight[w]
                         for w in words if w in self.word2vec] or
                        [np.zeros(self.dim)], axis=0)
                for words in X
            ])

In [ ]:
import gensim
from pythainlp import word_vector
from gensim.models import Word2Vec, KeyedVectors

# create word2vec for kt corpus
w2v_kt = Word2Vec(vector_size=300, min_count=1, window=4, workers=4)
w2v_kt.build_vocab(df_kt['processed'])
w2v_kt.train(df_kt['processed'], total_examples=w2v_kt.corpus_count, epochs=100)
w2v_kt.wv.most_similar("บะหมี่")

In [ ]:
w2v_tfidf_emb_kt = TfidfEmbeddingVectorizer(w2v_kt)
w2v_tifdf_fit_kt = w2v_tfidf_emb_kt.fit(df_kt['text'].apply(str))

# transfrom on both corpuses
text_w2v_tfidf_kt = w2v_tifdf_fit_kt.transform(df_kt['text'].apply(str))
text_w2v_tfidf_ws = w2v_tifdf_fit_kt.transform(df_ws['texts'].apply(str))

## POS Tagging


In [ ]:
# Implementation of exisiting pos-tagging techniques.  
# TODO: 1. test performance of ech

# concate word and tag with underscore (มัน_ADV)
def word_tag(pos):
    tag_list = []
    for item in pos:
        tag = ['_'.join(map(str, tups)) for tups in item]
        tag_list.append(' '.join(tag))
    return tag_list

# use only tag
def tag(pos):
    tag_list = []
    for item in pos:
        tmp = [el[1] for el in item]
        tag = ' '.join(map(str, tmp))
        tag_list.append(tag)
    return tag_list

# create custome tag for emoticon word
def tag_emoj(pos):
    tag_list = []
    
    for i in range(len(pos)):
        pl = [list(el) for el in pos[i]]
        tag_list.append(pl)

    for item in tag_list:
        for i, tag in enumerate(item):
            for j, word in enumerate(tag):
                if "EMJ" in word:
                    item[i][1] = "EMOJI"
    return tag_list

# this approach convert nest-list to simply list of word follows by tag ['word', 'NOUN']
def flatten(text):
    res = list(sum(text, ()))
    return res

In [ ]:
%%time
from pythainlp.tag import pos_tag_sents

pos = pos_tag_sents(df_kt['processed'].tolist(), corpus='orchid_ud')
pos = tag_emoj(pos)
df_kt['post_tag1'] = pd.DataFrame(tag(pos))
df_kt['post_tag2'] = pd.DataFrame(word_tag(pos))

pos = pos_tag_sents(df_ws['processed'].tolist(), corpus='orchid_ud')
pos = tag_emoj(pos)
df_ws['post_tag1'] = pd.DataFrame(tag(pos))
df_ws['post_tag2'] = pd.DataFrame(word_tag(pos))

print(df_ws[['processed', 'post_tag1']].iloc[1000:1010])
print("\n")
print(df_ws['post_tag2'].iloc[1000:1010])

In [ ]:
# create bow vectors
from sklearn.feature_extraction.text import CountVectorizer
bow1 = CountVectorizer(ngram_range=(1, 1))
#bow2 = CountVectorizer(ngram_range=(2, 2))

text_pos_bow1_fit_kt = bow1.fit(df_kt['post_tag1'])
text_pos_bow1_kt = text_pos_bow1_fit_kt.transform(df_kt['post_tag1'])
text_pos_bow1_ws = text_pos_bow1_fit_kt.transform(df_ws['post_tag1'])

# text_pos_bow2_fit_kt = bow2.fit(df_kt['post_tag1'])
# text_pos_bow2_kt = text_pos_bow2_fit_kt.transform(df_kt['post_tag2'])
# text_pos_bow2_ws = text_pos_bow2_fit_kt.transform(df_ws['post_tag2'])

print(text_pos_bow1_kt.toarray().shape,  text_pos_bow1_kt.toarray().shape)
print(text_pos_bow1_ws.toarray().shape,  text_pos_bow1_ws.toarray().shape)

# print(text_pos_bow2_kt.toarray().shape,  text_pos_bow2_kt.toarray().shape)
# print(text_pos_bow2_ws.toarray().shape,  text_pos_bow2_ws.toarray().shape)

In [ ]:
text_pos_bow1_ws.toarray()

In [ ]:
# create tfidf vectors
# tfidf1 = TfidfVectorizer(ngram_range=(1, 1))
# tfidf2 = TfidfVectorizer(ngram_range=(2, 2))

# text_pos_tfidf1_fit_kt = tfidf1.fit(df_kt['post_tag1'])
# text_pos_tfidf1_kt = text_pos_tfidf1_fit_kt.transform(df_kt['post_tag1'])
# text_pos_tfidf1_ws = text_pos_tfidf1_fit_kt.transform(df_ws['post_tag1'])

# text_pos_tfidf2_fit_kt = bow2.fit(df_kt['post_tag1'])
# text_pos_tfidf2_kt = text_pos_bow2_fit_kt.transform(df_kt['post_tag2'])
# text_pos_tfidf2_ws = text_pos_bow2_fit_kt.transform(df_ws['post_tag2'])

# print(text_pos_bow1_kt.toarray().shape,  text_pos_bow2_kt.toarray().shape)
# print(text_pos_bow1_ws.toarray().shape,  text_pos_bow2_ws.toarray().shape)

# print(text_pos_bow2_kt.toarray().shape,  text_pos_bow2_kt.toarray().shape)
# print(text_pos_bow2_ws.toarray().shape,  text_pos_bow2_ws.toarray().shape)

## Dictionary-based

In [ ]:
# load list of our custom positive and negative words
with open(os.path.dirname(os.getcwd()) + '\\data\\' + 'pos_words.txt', encoding='UTF-8') as f:
    pos_words = [line.rstrip('\n') for line in f]

with open(os.path.dirname(os.getcwd()) + '\\data\\' + 'neg_words.txt', encoding='UTF-8') as f:
    neg_words = [line.rstrip('\n') for line in f]
pos_words = list(set(pos_words))
neg_words = list(set(neg_words))

In [ ]:
bow1 = CountVectorizer(tokenizer=process_text, ngram_range=(1, 1))
bow2 = CountVectorizer(tokenizer=process_text, ngram_range=(2, 2))

my_vocabs = pos_words + neg_words
print('dict size: ', len(my_vocabs))

text_dict_bow1_fit = bow1.fit(my_vocabs)
text_dict_bow1_kt = text_dict_bow1_fit.transform(df_kt['text'].apply(str))
text_dict_bow1_ws = text_dict_bow1_fit.transform(df_ws['texts'].apply(str))

text_dict_bow2_fit = bow2.fit(my_vocabs)
text_dict_bow2_kt = text_dict_bow2_fit.transform(df_kt['text'].apply(str))
text_dict_bow2_ws = text_dict_bow2_fit.transform(df_ws['texts'].apply(str))

print(text_dict_bow1_kt.toarray().shape,  text_dict_bow1_kt.toarray().shape)
print(text_dict_bow1_ws.toarray().shape,  text_dict_bow1_ws.toarray().shape)

print(text_dict_bow2_kt.toarray().shape,  text_dict_bow2_kt.toarray().shape)
print(text_dict_bow2_ws.toarray().shape,  text_dict_bow2_ws.toarray().shape)

In [ ]:
tfidf1 = TfidfVectorizer(tokenizer=process_text, ngram_range=(1, 1))
tfidf2 = TfidfVectorizer(tokenizer=process_text, ngram_range=(2, 2))

text_dict_tfidf1_fit = tfidf1.fit(my_vocabs)
text_dict_tfidf1_kt = text_dict_tfidf1_fit.transform(df_kt['text'].apply(str))
text_dict_tfidf1_ws = text_dict_tfidf1_fit.transform(df_ws['texts'].apply(str))

text_dict_tfidf2_fit = tfidf2.fit(my_vocabs)
text_dict_tfidf2_kt = text_dict_tfidf2_fit.transform(df_kt['text'].apply(str))
text_dict_tfidf2_ws = text_dict_tfidf2_fit.transform(df_ws['texts'].apply(str))

print(text_dict_tfidf1_kt.toarray().shape,  text_dict_tfidf1_kt.toarray().shape)
print(text_dict_tfidf1_ws.toarray().shape,  text_dict_tfidf1_ws.toarray().shape)

print(text_dict_tfidf2_kt.toarray().shape,  text_dict_tfidf2_kt.toarray().shape)
print(text_dict_tfidf2_ws.toarray().shape,  text_dict_tfidf2_ws.toarray().shape)

## Save to disk

In [13]:
import scipy
import joblib
from scipy import sparse

In [29]:
y_t_kt = y_kt.to_numpy().reshape(-1, 1)
y_t_ws = y_ws.to_numpy().reshape(-1, 1)

y_t_kt = sparse.csr_matrix(y_t_kt)
y_t_ws = sparse.csr_matrix(y_t_ws)

In [ ]:
arr_bow1_kt = np.hstack((text_bow1_kt, y_t_kt))
arr_bow2_kt = np.hstack((text_bow2_kt, y_t_kt))
joblib.dump(arr_bow1_kt, model_path+'text_bow1_kt.pkl')
joblib.dump(arr_bow2_kt, model_path+'text_bow2_kt.pkl')

joblib.dump(lex_bow1_kt, lexicon_path+'lex_bow1_kt.pkl')
joblib.dump(lex_bow2_kt, lexicon_path+'lex_bow2_kt.pkl')

In [ ]:
arr_bow1_ws = np.hstack((text_bow1_ws, y_t_ws))
arr_bow2_ws = np.hstack((text_bow2_ws, y_t_ws))
joblib.dump(arr_bow1_ws, model_path+'text_bow1_ws.pkl')
joblib.dump(arr_bow2_ws, model_path+'text_bow2_ws.pkl')

joblib.dump(lex_bow1_ws, lexicon_path+'lex_bow1_ws.pkl')
joblib.dump(lex_bow2_ws, lexicon_path+'lex_bow2_ws.pkl')

In [ ]:
arr_tfidf1_kt = np.hstack((text_tfidf1_kt, y_t_kt))
arr_tfidf2_kt = np.hstack((text_tfidf2_kt, y_t_kt))
joblib.dump(arr_tfidf1_kt, model_path+'text_tfidf1_kt.pkl')
joblib.dump(arr_tfidf2_kt, model_path+'text_tfidf2_kt.pkl')

joblib.dump(lex_tfidf1_kt, lexicon_path+'lex_tfidf1_kt.pkl')
joblib.dump(lex_tfidf2_kt, lexicon_path+'lex_tfidf2_kt.pkl')

In [ ]:
arr_tfidf1_ws = np.hstack((text_tfidf1_ws, y_t_ws))
arr_tfidf2_ws = np.hstack((text_tfidf2_ws, y_t_ws))
joblib.dump(arr_tfidf1_ws, model_path+'text_tfidf1_ws.pkl')
joblib.dump(arr_tfidf2_ws, model_path+'text_tfidf2_ws.pkl')

joblib.dump(lex_tfidf1_ws, lexicon_path+'lex_tfidf1_ws.pkl')
joblib.dump(lex_tfidf2_ws, lexicon_path+'lex_tfidf2_ws.pkl')

In [ ]:
arr_w2v_tfidf_kt = np.hstack(( sparse.csr_matrix(text_w2v_tfidf_kt), y_t_kt))
arr_w2v_tfidf_ws = np.hstack(( sparse.csr_matrix(text_w2v_tfidf_ws), y_t_ws))
joblib.dump(arr_w2v_tfidf_kt, model_path+'text_w2v_tfidf_kt.pkl')
joblib.dump(arr_w2v_tfidf_ws, model_path+'text_w2v_tfidf_ws.pkl')

In [ ]:
arr_pos_bow1_kt = np.hstack((text_pos_bow1_kt, y_t_kt))
#arr_pos_bow2_kt = np.hstack((text_pos_bow2_kt, y_t_kt))
joblib.dump(arr_pos_bow1_kt, model_path+'text_pos_bow1_kt.pkl')
#joblib.dump(arr_pos_bow2_kt, model_path+'text_pos_bow2_kt.pkl')

In [ ]:
arr_pos_bow1_ws = np.hstack((text_pos_bow1_ws, y_t_ws))
#arr_pos_bow2_ws = np.hstack((text_pos_bow2_ws, y_t_ws))
joblib.dump(arr_pos_bow1_ws, model_path+'text_pos_bow1_ws.pkl')
#joblib.dump(arr_pos_bow2_ws, model_path+'text_pos_bow2_ws.pkl')

In [ ]:
# arr_pos_tfidf1_kt = np.hstack((text_pos_tfidf1_kt, y_t_kt))
# arr_pos_tfidf2_kt = np.hstack((text_pos_tfidf2_kt, y_t_kt))
# joblib.dump(arr_pos_tfidf1_kt, model_path+'text_pos_tfidf1_kt.pkl')
# joblib.dump(arr_pos_tfidf2_kt, model_path+'text_pos_tfidf2_kt.pkl')

In [ ]:
# arr_pos_tfidf1_ws = np.hstack((text_pos_tfidf1_ws, y_t_ws))
# arr_pos_tfidf2_ws = np.hstack((text_pos_tfidf2_ws, y_t_ws))
# joblib.dump(arr_pos_tfidf1_ws, model_path+'text_pos_tfidf1_ws.pkl')
# joblib.dump(arr_pos_tfidf2_ws, model_path+'text_pos_tfidf2_ws.pkl')

In [ ]:
arr_dict_bow1_kt = np.hstack((text_dict_bow1_kt, y_t_kt))
arr_dict_bow2_kt = np.hstack((text_dict_bow2_kt, y_t_kt))
joblib.dump(arr_dict_bow1_kt, model_path+'text_dict_bow1_kt.pkl')
joblib.dump(arr_dict_bow2_kt, model_path+'text_dict_bow2_kt.pkl')

In [ ]:
arr_dict_bow1_ws = np.hstack((text_dict_bow1_ws, y_t_ws))
arr_dict_bow2_ws = np.hstack((text_dict_bow2_ws, y_t_ws))
joblib.dump(arr_dict_bow1_ws, model_path+'text_dict_bow1_ws.pkl')
joblib.dump(arr_dict_bow2_ws, model_path+'text_dict_bow2_ws.pkl')

In [ ]:
arr_dict_tfidf1_kt = np.hstack((text_dict_tfidf1_kt, y_t_kt))
arr_dict_tfidf2_kt = np.hstack((text_dict_tfidf2_kt, y_t_kt))
joblib.dump(arr_dict_tfidf1_kt, model_path+'text_dict_tfidf1_kt.pkl')
joblib.dump(arr_dict_tfidf2_kt, model_path+'text_dict_tfidf2_kt.pkl')

In [ ]:
arr_dict_tfidf1_ws = np.hstack((text_dict_tfidf1_ws, y_t_ws))
arr_dict_tfidf2_ws = np.hstack((text_dict_tfidf2_ws, y_t_ws))
joblib.dump(arr_dict_tfidf1_ws, model_path+'text_dict_tfidf1_ws.pkl')
joblib.dump(arr_dict_tfidf2_ws, model_path+'text_dict_tfidf2_ws.pkl')

## Demonstrate usage


In [26]:
# load kt corpus extracted features array 
#arr_kt = np.load(model_path+'text_tfidf2_kt.joblib')
    
item = joblib.load(model_path+'text_bow1_kt.pkl')

In [32]:
#arr_kt = np.concatenate((item[0].A, item[1].A), axis=1)
arr_bow1_kt = np.hstack((text_bow1_kt, y_t_kt))
#arr_kt = np.concatenate(text_bow1_kt, y_t_kt)
arr_kt = np.concatenate((arr_bow1_kt[0].A, arr_bow1_kt[1].A), axis=1)

## Train-test split

In [33]:
from sklearn.model_selection import train_test_split, cross_val_score
train_df, test_df = train_test_split(arr_kt, test_size=0.20, random_state=42)
train_df.shape, test_df.shape

((48064, 1395), (12017, 1395))

## Train-valid split

In [34]:
X_train, X_valid, y_train, y_valid = train_test_split(train_df[:,:-1], train_df[:,-1], test_size=0.15, random_state=42)
X_train.shape, X_valid.shape, y_train.shape, y_valid.shape

((40854, 1394), (7210, 1394), (40854,), (7210,))

## Test the extracted features with Logistic Regression

In [35]:
# quick test with out cv
#fit logistic regression models
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(C=2., penalty="l2", solver="liblinear", dual=False, multi_class="ovr")
model.fit(X_train, y_train)
model.score(X_valid, y_valid)
#y_pred = model.predict(X_valid)

0.6694868238557559

In [36]:
from sklearn.metrics import confusion_matrix, accuracy_score, f1_score, precision_score, recall_score, classification_report
def build_model(model):
    scores = (cross_val_score(model, X_train, y_train, cv = 5).mean())
    model = model.fit(X_train, y_train)
    y_pred = model.predict(X_valid)
    acc_sc = accuracy_score(y_valid, y_pred)
    pre_sc = precision_score(y_valid, y_pred, average='weighted')
    rec_sc = recall_score(y_valid, y_pred, average='weighted')
    f1_sc = f1_score(y_valid, y_pred, average='weighted')
    print('Accuracy :',acc_sc)
    print('Confusion Matrix :\n', confusion_matrix(y_valid, y_pred))
    print('Precision :', pre_sc)
    print('Recall :', rec_sc)
    print('F1-score :', f1_sc)
    print('Classification Report :\n', classification_report(y_valid, y_pred))
    print('Average accuracy of k-fold (5-fold) :', scores ,'\n')

In [37]:
build_model(model)

Accuracy : 0.6694868238557559
Confusion Matrix :
 [[ 208  902   71]
 [ 122 4184  204]
 [  63 1021  435]]
Precision : 0.6443251170595544
Recall : 0.6694868238557559
F1-score : 0.6185379590395134
Classification Report :
               precision    recall  f1-score   support

           0       0.53      0.18      0.26      1181
           1       0.69      0.93      0.79      4510
           2       0.61      0.29      0.39      1519

    accuracy                           0.67      7210
   macro avg       0.61      0.46      0.48      7210
weighted avg       0.64      0.67      0.62      7210

Average accuracy of k-fold (5-fold) : 0.6694325410027732 



In [38]:
# predict on kt dataset
#arr_ws = np.load(model_path+'text_tfidf2_ws.npy')
item = joblib.load(model_path+'text_tfidf2_ws.pkl')
arr_ws = np.concatenate((item[0].A, item[1].A), axis=1)
arr_ws.shape

(26737, 17304)

In [39]:
train_df, test_df = train_test_split(arr_ws, test_size=0.20, random_state=42)
train_df.shape, test_df.shape

((21389, 17304), (5348, 17304))

In [40]:
X_train, X_valid, y_train, y_valid = train_test_split(train_df[:,:-1], train_df[:,-1], test_size=0.15, random_state=42)
X_train.shape, X_valid.shape, y_train.shape, y_valid.shape

((18180, 17303), (3209, 17303), (18180,), (3209,))

In [41]:
build_model(model)

Accuracy : 0.6251168588345279
Confusion Matrix :
 [[ 327  442   21    0]
 [ 116 1571   67    5]
 [  43  426  107    2]
 [   2   76    3    1]]
Precision : 0.6078938333813285
Recall : 0.6251168588345279
F1-score : 0.5791858773594074
Classification Report :
               precision    recall  f1-score   support

         0.0       0.67      0.41      0.51       790
         1.0       0.62      0.89      0.74      1759
         2.0       0.54      0.19      0.28       578
         3.0       0.12      0.01      0.02        82

    accuracy                           0.63      3209
   macro avg       0.49      0.38      0.39      3209
weighted avg       0.61      0.63      0.58      3209

Average accuracy of k-fold (5-fold) : 0.6190319031903191 

