## Explore difference POS tagging strategy that available 

In [1]:
import pandas as pd
import ast
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, LabelBinarizer
from pythainlp.tag import pos_tag_sents
from src.feature.postag_transform import onehot_mean, word_tag, tag, tag_emoj, flatten

In [2]:
df = pd.read_csv('C:\\Users\\Pree\\Thai_SA_journal\\data\\processed\\wisesight.csv')

In [3]:
feat = df['processed'].iloc[1000:1100]
tagged = pos_tag_sents(feat.apply(ast.literal_eval).values.tolist(), corpus='orchid_ud')

In [4]:
tagged[10:20]

[[('ค่า', 'NOUN'),
  ('ชุด', 'NOUN'),
  ('แพง', 'ADJ'),
  ('กว่า', 'SCONJ'),
  ('ค่า', 'NOUN'),
  ('กิน', 'VERB'),
  ('อิ้ก', 'NOUN'),
  ('xxrep', 'NOUN')],
 [('ค่าเช่า', 'NOUN'),
  ('ชุด', 'NOUN'),
  ('แพ', 'NOUN'),
  ('งก', 'NOUN'),
  ('ว่าที่', 'SCONJ'),
  ('ลด', 'VERB'),
  ('อีก', 'ADV')],
 [('คิว', 'NOUN'),
  ('เอม', 'NOUN'),
  ('เค', 'NOUN'),
  ('นาน', 'ADJ'),
  ('มาก', 'ADV'),
  ('อี', 'NOUN'),
  ('ห่า', 'NOUN'),
  ('กุ', 'NOUN'),
  ('หิว', 'NOUN')],
 [('คือ', 'VERB'),
  ('มัน', 'PRON'),
  ('มี', 'VERB'),
  ('บ่อย', 'NOUN'),
  ('แต่', 'CCONJ'),
  ('ไม่', 'PART'),
  ('พา', 'VERB'),
  ('ไป', 'AUX'),
  ('ไง', 'NOUN')],
 [('เคมี', 'NOUN'),
  ('ภัณ', 'NOUN'),
  ('พวก', 'NOUN'),
  ('อาหาร', 'NOUN'),
  ('ยา', 'ADJ'),
  ('ก็', 'SCONJ'),
  ('ผิด', 'ADJ'),
  ('ดิ', 'NOUN')],
 [('เค้า', 'NOUN'),
  ('ปิด', 'VERB'),
  ('สาขา', 'NOUN'),
  ('ทั่ว', 'ADV'),
  ('ภาคใต้', 'NOUN'),
  ('แล้ว', 'AUX')],
 [('เค้า', 'NOUN'),
  ('เรียก', 'VERB'),
  ('ว่า', 'SCONJ'),
  ('โกง', 'NOUN'),
  ('ได้', 'AUX'),

# Use only tags

In [5]:
pos_tag = tag(tagged) 

In [6]:
pos_tag[10:20]

['NOUN NOUN ADJ SCONJ NOUN VERB NOUN NOUN',
 'NOUN NOUN NOUN NOUN SCONJ VERB ADV',
 'NOUN NOUN NOUN ADJ ADV NOUN NOUN NOUN NOUN',
 'VERB PRON VERB NOUN CCONJ PART VERB AUX NOUN',
 'NOUN NOUN NOUN NOUN ADJ SCONJ ADJ NOUN',
 'NOUN VERB NOUN ADV NOUN AUX',
 'NOUN VERB SCONJ NOUN AUX VERB NOUN',
 'NOUN NOUN VERB NOUN VERB NOUN NOUN',
 'NOUN VERB DET NOUN NOUN AUX VERB NOUN',
 'NOUN NOUN NOUN NOUN NOUN NOUN NOUN NOUN NOUN']

# Join word and tag

In [7]:
pos_tag = word_tag(tagged)
print(pos_tag)

['ไก่_NOUN เค็ม_VERB ไป_AUX นะ_VERB ครับ_NOUN ไม่_PART ชอบ_VERB เลย_ADV', 'ไก่_NOUN เคเอฟซี_NOUN หร่อย_ADJ กว่า_SCONJ แมค_NOUN จืด_NOUN', 'ของ_ADP น้อย_ADV มาก_ADV ชู_NOUN ชิ_NOUN อ่ะ_NOUN โฮมโปร_NOUN', 'ขอ_VERB ใบ_VERB อนุ_NOUN ญาติ_NOUN เป็น_VERB นัก_NOUN ปั่น_NOUN ลวด_NOUN', 'ขอร้อง_NOUN ละ_ADP ตัวหนังสือ_NOUN ถี่_ADJ จัง_ADV', 'ขุด_NOUN ทางเท้า_NOUN ตอน_NOUN ห้า_NUM ครึ่ง_NUM อะนะ_ADV', 'ควย_NOUN วันนั้น_NOUN จะ_AUX พา_VERB ใป_ADP แดก_NOUN ใม่ใป_NOUN', 'คอม_NOUN เพล็ก_NOUN มัน_PRON ไม่_PART มี_VERB กระทะทอง_NOUN', 'ค่า_NOUN ชุด_NOUN ก็_SCONJ เกิน_VERB ค่า_NOUN กิน_VERB ละ_ADP มั้ง_ADV', 'ค่า_NOUN ชุด_NOUN ไทย_NOUN แพง_ADJ กว่า_SCONJ ส่วนลด_NOUN EMJpersevering-faceEMJ_NOUN', 'ค่า_NOUN ชุด_NOUN แพง_ADJ กว่า_SCONJ ค่า_NOUN กิน_VERB อิ้ก_NOUN xxrep_NOUN', 'ค่าเช่า_NOUN ชุด_NOUN แพ_NOUN งก_NOUN ว่าที่_SCONJ ลด_VERB อีก_ADV', 'คิว_NOUN เอม_NOUN เค_NOUN นาน_ADJ มาก_ADV อี_NOUN ห่า_NOUN กุ_NOUN หิว_NOUN', 'คือ_VERB มัน_PRON มี_VERB บ่อย_NOUN แต่_CCONJ ไม่_PART พา_VERB ไป_AUX ไง_NOUN', 'เคม

# Flatten approach

In [8]:
pos = flatten(tagged)
pos

[['ไก่',
  'NOUN',
  'เค็ม',
  'VERB',
  'ไป',
  'AUX',
  'นะ',
  'VERB',
  'ครับ',
  'NOUN',
  'ไม่',
  'PART',
  'ชอบ',
  'VERB',
  'เลย',
  'ADV'],
 ['ไก่',
  'NOUN',
  'เคเอฟซี',
  'NOUN',
  'หร่อย',
  'ADJ',
  'กว่า',
  'SCONJ',
  'แมค',
  'NOUN',
  'จืด',
  'NOUN'],
 ['ของ',
  'ADP',
  'น้อย',
  'ADV',
  'มาก',
  'ADV',
  'ชู',
  'NOUN',
  'ชิ',
  'NOUN',
  'อ่ะ',
  'NOUN',
  'โฮมโปร',
  'NOUN'],
 ['ขอ',
  'VERB',
  'ใบ',
  'VERB',
  'อนุ',
  'NOUN',
  'ญาติ',
  'NOUN',
  'เป็น',
  'VERB',
  'นัก',
  'NOUN',
  'ปั่น',
  'NOUN',
  'ลวด',
  'NOUN'],
 ['ขอร้อง',
  'NOUN',
  'ละ',
  'ADP',
  'ตัวหนังสือ',
  'NOUN',
  'ถี่',
  'ADJ',
  'จัง',
  'ADV'],
 ['ขุด',
  'NOUN',
  'ทางเท้า',
  'NOUN',
  'ตอน',
  'NOUN',
  'ห้า',
  'NUM',
  'ครึ่ง',
  'NUM',
  'อะนะ',
  'ADV'],
 ['ควย',
  'NOUN',
  'วันนั้น',
  'NOUN',
  'จะ',
  'AUX',
  'พา',
  'VERB',
  'ใป',
  'ADP',
  'แดก',
  'NOUN',
  'ใม่ใป',
  'NOUN'],
 ['คอม',
  'NOUN',
  'เพล็ก',
  'NOUN',
  'มัน',
  'PRON',
  'ไม่',
  'PART',
  'มี'

# One-hot encoded vector for each POS

In [9]:
import numpy as np
pos_tag_ud = ['ADJ', 'ADP', 'ADV', 'AUX', 'CCONJ', 'DET', 'INTJ', 'NOUN', 'NUM', 'PART', 'PRON', 'PUNCT', 'SCONJ', 'SYM', 'VERB', 'X']
pos_tag_arr = np.array(pos_tag_ud)

le = LabelEncoder().fit(pos_tag_arr )
integery_data = le.transform(pos_tag_arr )
ohe = OneHotEncoder().fit(integery_data.reshape((-1,1)))
onehot_data = ohe.transform(integery_data.reshape((-1,1)))

In [10]:
texty_data = np.array(pos_tag_ud)
lb = LabelBinarizer().fit(texty_data)
onehot_data = lb.transform(texty_data)
print(onehot_data, lb.inverse_transform(onehot_data))

[[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]] ['ADJ' 'ADP' 'ADV' 'AUX' 'CCONJ' 'DET' 'INTJ' 'NOUN' 'NUM' 'PART' 'PRON'
 'PUNCT' 'SCONJ' 'SYM' 'VERB' 'X']


In [11]:
tagged[0]

[('ไก่', 'NOUN'),
 ('เค็ม', 'VERB'),
 ('ไป', 'AUX'),
 ('นะ', 'VERB'),
 ('ครับ', 'NOUN'),
 ('ไม่', 'PART'),
 ('ชอบ', 'VERB'),
 ('เลย', 'ADV')]

In [12]:
tmp = [el[1] for el in tagged[0]]
tag_only = ' '.join(map(str, tmp))

In [13]:
tag_only

'NOUN VERB AUX VERB NOUN PART VERB ADV'

In [14]:
tag_data = list(tag_only.split(" "))
tag_data

['NOUN', 'VERB', 'AUX', 'VERB', 'NOUN', 'PART', 'VERB', 'ADV']

In [15]:
texty_data = np.array(tag_data)
onehot_data = lb.transform(texty_data)
print(onehot_data, lb.inverse_transform(onehot_data))

[[0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
 [0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]] ['NOUN' 'VERB' 'AUX' 'VERB' 'NOUN' 'PART' 'VERB' 'ADV']


In [ ]:
# now deal with n tagged as a function
import numpy as np
def onehot_label(tagged):
        pos_tag_ud = ['ADJ', 'ADP', 'ADV', 'AUX', 'CCONJ', 'DET', 'INTJ', 'NOUN', 'NUM', 'PART', 'PRON', 'PUNCT', 'SCONJ', 'SYM', 'VERB', 'X']
        pos_tag_ud_arr = np.array(pos_tag_ud)
        tag_list = []
    
        for item in tagged:
                lb = LabelBinarizer().fit(pos_tag_ud_arr)
                tmp = [el[1] for el in item]
                tag_only = ' '.join(map(str, tmp))
                onehot_data = lb.transform(tag_only)
                tag_list.append(onehot_data)
        return  tag_list
    